services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - BLUEPRINT_DB_HOST=psql_bp
      - BLUEPRINT_DB_PORT=5432
      - BLUEPRINT_DB_DATABASE=${BLUEPRINT_DB_DATABASE}
      - BLUEPRINT_DB_USERNAME=${BLUEPRINT_DB_USERNAME}
      - BLUEPRINT_DB_PASSWORD=${BLUEPRINT_DB_PASSWORD}
    depends_on:
      - psql_bp

  psql_bp:
    image: postgres:latest
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp:
